theme: jekyll-theme-minimal
title: My Personal projects
description: This github page is in the works, and will currently display projects I have done

markdown: kramdown
plugins:
- jekyll-seo-tag
- jekyll-sitemap
include:
- assets/css/style.css
