theme: jekyll-theme-minimal
title: Installing ArchLinux via VirtualBox
description: This page explains my documentation of the installation process for installing ArchLinux.

markdown: kramdown

include:
- assets/css/style.css
